apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICAgImF1dGhzIjogewogICAgICAgICJnaGNyLmlvIjogewogICAgICAgICAgICAiYXV0aCI6ICJUbWxyYjJ4aGVWbGhhMjkyYkdWMk9tZG9jRjk0Ym1jMlJUUm9Na2N5VVdGVlVVeFJUVXB0Wkc5YWEwZzVNbk14U0RNeU5FZEZaMk09IgogICAgICAgIH0KICAgIH0sCiAgICAiY3JlZHNTdG9yZSI6ICJkZXNrdG9wIiwKICAgICJjdXJyZW50Q29udGV4dCI6ICJkZXNrdG9wLWxpbnV4Igp9
type: kubernetes.io/dockerconfigjson
